"""
Django settings for PoemTalk project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(_file_)))
# 将我们自己定义的包加入到python的环境变量里
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
# sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&c61b8wdu7o+ue)a1e1(81tfy10%0+#8kv(@&-2-=*i1*&&!a%'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
# DEBUG = True 表示测试阶段 False是线上环境
DEBUG = True
# ALLOWED_HOSTS = ['*']
#

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'poem.apps.PoemConfig',
    'poet.apps.PoetConfig',
    'exams.apps.ExamsConfig',
    'zhaomin.apps.ZhaominConfig',
    'operations.apps.OperationsConfig',
    'bbs.apps.BbsConfig',
    'testapp.apps.TestappConfig',
    'crispy_forms',
    'captcha',
    # 'DjangoUeditor',
    # 'smart_chart.echart'
]
AUTH_USER_MODEL='users.UserProfile'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PoemTalk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'PoemTalk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shishuo',
        'USER':'zhaomin',
        'PASSWORD':'zhaomin182',
        'HOST':'localhost',
        'PORT':3306,
'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
    },
# 修改settings.py,在配置DATABASES中，添加以下代码,取消外键检查
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }

}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# 静态文件和媒体文件
# STATIC_URL = '/static/static/'
# STATICFILES_DIRS=[
#     os.path.join(BASE_DIR,'static')
# ]
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]

MEDIA_URL='/static/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static/media')

# EMAIL_HOST='smtp.qq.com'
# EMAIL_PORT=587
EMAIL_HOST='smtp.163.com'
EMAIL_PORT=25
EMAIL_HOST_USER='diy1830817543@163.com'
EMAIL_HOST_PASSWORD='HOMNGYRYNRGSDRGK'
EMAIL_FROM='diy1830817543@163.com'
