# Generated by Django 2.1.4 on 2021-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_true',
            field=models.BooleanField(default=False, verbose_name='是否为真'),
        ),
    ]
