# Generated by Django 2.1.4 on 2021-01-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_true',
        ),
    ]
