# Generated by Django 2.1.4 on 2021-02-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210131_2338'),
        ('users', '0004_remove_userprofile_is_true'),
    ]

    operations = [
    ]
