# Generated by Django 2.1.4 on 2021-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210201_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(default=0, verbose_name='考试状态'),
        ),
    ]
