# Generated by Django 2.1.4 on 2021-03-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210216_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, default='童生', max_length=20, null=True, verbose_name='用户昵称'),
        ),
    ]
