# Generated by Django 2.1.4 on 2021-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210301_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfo',
            name='url',
            field=models.URLField(default='http://www.baidu.com', verbose_name='图片链接'),
        ),
    ]
