# Generated by Django 2.1.4 on 2021-05-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_userprofile_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerInfo',
        ),
    ]
