# Generated by Django 2.1.4 on 2021-01-25 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_text', models.CharField(max_length=30, verbose_name='题干')),
                ('answer', models.CharField(max_length=30, verbose_name='答案')),
                ('value', models.IntegerField(default=0, verbose_name='分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '题干信息',
                'verbose_name_plural': '题干信息',
            },
        ),
        migrations.CreateModel(
            name='PoemTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_type', models.CharField(max_length=10, verbose_name='题目种类')),
                ('image', models.ImageField(max_length=200, upload_to='testapp/', verbose_name='诗词封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '题目种类',
                'verbose_name_plural': '题目种类',
            },
        ),
        migrations.CreateModel(
            name='PoetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='poet/', verbose_name='作者头像')),
                ('name', models.CharField(max_length=20, verbose_name='作者姓名')),
                ('address', models.CharField(max_length=20, verbose_name='所属朝代')),
                ('poem_style', models.CharField(max_length=20, verbose_name='诗词风格')),
                ('poemtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.PoemTest', verbose_name='所属种类')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
            },
        ),
        migrations.AddField(
            model_name='poeminfo',
            name='poemtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.PoemTest', verbose_name='所属种类'),
        ),
    ]
