# Generated by Django 2.1.4 on 2021-02-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemtest',
            name='category',
            field=models.CharField(choices=[('bqsj', '补全诗句'), ('twpp', '图文匹配'), ('dzcs', '点字成诗')], default='', max_length=10, verbose_name='题目类别'),
        ),
    ]
