# Generated by Django 2.1.4 on 2021-02-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210205_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_e',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_f',
        ),
    ]
