# Generated by Django 2.1.4 on 2021-02-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210222_2038'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='question',
    #         name='note',
    #     ),
    # ]
