# Generated by Django 2.1.4 on 2021-02-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20210222_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_ans',
            field=models.TextField(default='', verbose_name='用户答案'),
        ),
    ]
