# Generated by Django 2.1.4 on 2021-03-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20210325_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('single_choice', '选择题'), ('judgment', '判断题')], default='single_choice', max_length=20, verbose_name='题目类型'),
        ),
    ]
