# Generated by Django 2.1.4 on 2021-03-25 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20210325_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlist',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='question',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='boolf',
            field=models.TextField(default='错', null=True, verbose_name='判断正误错误选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='boolt',
            field=models.TextField(default='对', null=True, verbose_name='判断正误正确选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.TextField(default='A.', null=True, verbose_name='A选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.TextField(default='B.', null=True, verbose_name='B选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.TextField(default='C.', null=True, verbose_name='C选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.TextField(default='D.', null=True, verbose_name='D选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_num',
            field=models.IntegerField(default=4, null=True, verbose_name='选项数'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(null=True, verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('single_choice', '选择题'), ('judgment', '判断题')], default='single_choice', max_length=20, null=True, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_ans',
            field=models.TextField(default='', null=True, verbose_name='用户答案'),
        ),
    ]
