# Generated by Django 2.1.4 on 2021-03-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20210331_1532'),
        ('testapp', '0010_auto_20210325_2053'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='paper',
        #     name='course',
        # ),
        # migrations.RemoveField(
        #     model_name='paper',
        #     name='paper_name',
        # ),
        # migrations.RemoveField(
        #     model_name='paper',
        #     name='question',
        # ),
        # migrations.RemoveField(
        #     model_name='paperlist',
        #     name='course',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='course',
        # ),
        # migrations.DeleteModel(
        #     name='CourseList',
        # ),
        # migrations.DeleteModel(
        #     name='Paper',
        # ),
        # migrations.DeleteModel(
        #     name='PaperList',
        # ),
        # migrations.DeleteModel(
        #     name='Question',
        # ),
    ]
