# Generated by Django 2.1.4 on 2021-03-31 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0011_auto_20210331_1532'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CourseList',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(default='', max_length=100, verbose_name='科目名')),
        #         ('decs', models.CharField(default='', max_length=500, verbose_name='科目说明')),
        #         ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
        #     ],
        #     options={
        #         'verbose_name': '考试科目',
        #         'verbose_name_plural': '考试科目',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Paper',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
        #         ('score', models.IntegerField(default=0, verbose_name='分值')),
        #         ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='所属课程')),
        #     ],
        #     options={
        #         'verbose_name': '试题列表',
        #         'verbose_name_plural': '试题列表',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PaperList',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(default='', max_length=100, verbose_name='试卷名')),
        #         ('is_allow', models.BooleanField(default=False, verbose_name='启用随机组卷')),
        #         ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='开考时间')),
        #         ('single_choice_num', models.IntegerField(default=0, verbose_name='单选题数')),
        #         ('single_choice_score', models.IntegerField(default=0, verbose_name='单选分值')),
        #         ('judgment', models.IntegerField(default=0, verbose_name='判断题数')),
        #         ('judgment_score', models.IntegerField(default=0, verbose_name='判断分值')),
        #         ('random_paper', models.BooleanField(default=True, verbose_name='随机卷')),
        #         ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='所属课程')),
        #     ],
        #     options={
        #         'verbose_name': '试卷列表',
        #         'verbose_name_plural': '试卷列表',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Question',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('questionType', models.CharField(choices=[('single_choice', '选择题'), ('judgment', '判断题')], default='single_choice', max_length=20, null=True, verbose_name='题目类型')),
        #         ('content', models.TextField(null=True, verbose_name='题目内容')),
        #         ('answer', models.TextField(null=True, verbose_name='正确答案')),
        #         ('user_ans', models.TextField(default='', null=True, verbose_name='用户答案')),
        #         ('choice_a', models.TextField(default='A.', null=True, verbose_name='A选项')),
        #         ('choice_b', models.TextField(default='B.', null=True, verbose_name='B选项')),
        #         ('choice_c', models.TextField(default='C.', null=True, verbose_name='C选项')),
        #         ('choice_d', models.TextField(default='D.', null=True, verbose_name='D选项')),
        #         ('boolt', models.TextField(default='对', null=True, verbose_name='判断正误正确选项')),
        #         ('boolf', models.TextField(default='错', null=True, verbose_name='判断正误错误选项')),
        #         ('choice_num', models.IntegerField(default=4, null=True, verbose_name='选项数')),
        #         ('add_time', models.DateField(default=datetime.datetime.now, null=True, verbose_name='添加时间')),
        #         ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='考试科目')),
        #     ],
        #     options={
        #         'verbose_name': '题库',
        #         'verbose_name_plural': '题库',
        #     },
        # ),
        migrations.AddField(
            model_name='paper',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.PaperList', verbose_name='试卷名称'),
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Question', verbose_name='题目'),
        ),
    ]
