# Generated by Django 2.1.4 on 2021-03-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20210331_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='note',
        ),
    ]
