# Generated by Django 3.1.5 on 2021-01-23 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poem', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoem',
            name='study_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学习用户'),
        ),
        migrations.AddField(
            model_name='userpoem',
            name='study_poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.poem', verbose_name='学习诗词'),
        ),
        migrations.AddField(
            model_name='userlove',
            name='love_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='comment_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='comment_poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.poem', verbose_name='评论诗词'),
        ),
        migrations.AlterUniqueTogether(
            name='userpoem',
            unique_together={('study_man', 'study_poem')},
        ),
    ]
