# Generated by Django 2.1.4 on 2021-02-05 23:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0003_auto_20210205_2337'),
        ('operations', '0002_auto_20210123_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_choice_num', models.IntegerField(default=1, verbose_name='单选题数')),
                ('sin_choice_sco', models.IntegerField(default=1, verbose_name='单选分值')),
                ('mul_choice_num', models.IntegerField(default=2, verbose_name='多选题数')),
                ('mul_choice_sco', models.IntegerField(default=2, verbose_name='多选分值')),
                ('jud_num', models.IntegerField(default=1, verbose_name='判断题数')),
                ('jud_sco', models.IntegerField(default=1, verbose_name='判断分值')),
                ('sho_num', models.IntegerField(default=1, verbose_name='简答题数')),
                ('sho_sco', models.IntegerField(default=10, verbose_name='简答分值')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='所属课程')),
                ('paper_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.PaperList', verbose_name='试卷名称')),
            ],
            options={
                'verbose_name': '试题列表',
                'verbose_name_plural': '试题列表',
            },
        ),
        migrations.CreateModel(
            name='PaperCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(verbose_name='题目')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '试题临时列表',
                'verbose_name_plural': '试题临时列表',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='用户答案')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='作答时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='课程')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Paper', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户做题记录',
                'verbose_name_plural': '用户做题记录',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='录入时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='课程')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='录入时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.CourseList', verbose_name='课程')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
