# Generated by Django 2.1.4 on 2021-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_create_paper_papercache_useranswerlog_usercollection_userrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerlog',
            name='paper_name',
            field=models.CharField(default='', max_length=20, verbose_name='试卷名称'),
        ),
    ]
