# Generated by Django 2.1.4 on 2021-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210228_2134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlemodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table=None,
        ),
    ]
