# Generated by Django 2.1.4 on 2021-03-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20210302_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.UserComment'),
        ),
    ]
