# Generated by Django 2.1.4 on 2021-03-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20210321_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='parent',
        ),
    ]
