# Generated by Django 2.1.4 on 2021-03-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_remove_usercomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='parent',
        ),
    ]
