# Generated by Django 2.1.4 on 2021-04-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_remove_articlemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='comment_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.ArticleModel', verbose_name='评论帖子'),
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
