# Generated by Django 2.1.4 on 2021-05-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20210427_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAsk',
        ),
    ]
