# Generated by Django 2.1.4 on 2021-05-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_delete_userask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswerlog',
            name='answer',
        ),
    ]
