# Generated by Django 2.1.4 on 2021-05-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_remove_useranswerlog_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_paper',
            name='course',
        ),
        migrations.RemoveField(
            model_name='create_paper',
            name='paper_name',
        ),
        migrations.DeleteModel(
            name='Create_Paper',
        ),
    ]
