# Generated by Django 2.1.4 on 2021-06-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20210531_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
