# Generated by Django 2.1.4 on 2021-06-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0010_auto_20210531_1738'),
        ('poet', '0005_auto_20210603_2037'),
        ('operations', '0025_auto_20210614_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlove',
            name='love_poem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.Poem', verbose_name='收藏诗词'),
        ),
        migrations.AddField(
            model_name='userlove',
            name='love_poet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poet.PoetInfo', verbose_name='收藏用户'),
        ),
    ]
