# Generated by Django 2.1.4 on 2021-06-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_auto_20210615_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlove',
            name='love_poem',
            field=models.CharField(default='', max_length=50, verbose_name='收藏诗词'),
        ),
        migrations.AlterField(
            model_name='userlove',
            name='love_poet',
            field=models.CharField(default='', max_length=50, verbose_name='收藏诗人'),
        ),
    ]
