# Generated by Django 3.1.5 on 2021-01-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='poet/', verbose_name='作者头像')),
                ('name', models.CharField(max_length=20, verbose_name='作者姓名')),
                ('address', models.CharField(max_length=20, verbose_name='所属朝代')),
                ('poem_style', models.CharField(max_length=20, verbose_name='诗词风格')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
            },
        ),
    ]
