# Generated by Django 2.1.4 on 2021-03-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0002_auto_20210306_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetinfo',
            name='story',
        ),
    ]
