# Generated by Django 2.1.4 on 2021-06-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0004_poetinfo_love_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poetinfo',
            options={'verbose_name': '诗人信息', 'verbose_name_plural': '诗人信息'},
        ),
    ]
