# Generated by Django 2.1.4 on 2021-03-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_user_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_e',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_f',
        ),
    ]
