# Generated by Django 2.1.4 on 2021-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210330_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_e',
            field=models.TextField(default='E.', verbose_name='E选项'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_f',
            field=models.TextField(default='F.', verbose_name='F选项'),
        ),
    ]
