# Generated by Django 2.1.4 on 2021-04-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_remove_useranswerlog_paper'),
        ('exams', '0004_auto_20210330_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='question',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
