# Generated by Django 2.1.4 on 2021-05-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20210424_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperlist',
            name='multiple_choice_num',
        ),
        migrations.RemoveField(
            model_name='paperlist',
            name='multiple_choice_score',
        ),
    ]
