# Generated by Django 2.1.4 on 2021-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20210525_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_e',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_f',
        ),
        migrations.AlterField(
            model_name='question',
            name='user_ans',
            field=models.TextField(default='暂无', null=True, verbose_name='用户答案'),
        ),
    ]
