# Generated by Django 2.1.4 on 2021-06-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_question_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('single_choice', '选择题'), ('judgment', '判断题')], default='single_choice', max_length=20, verbose_name='题目类型'),
        ),
    ]
