# Generated by Django 2.1.4 on 2021-06-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20210612_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselist',
            options={'verbose_name': '测试类别', 'verbose_name_plural': '测试类别'},
        ),
    ]
