# Generated by Django 2.1.4 on 2021-06-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20210612_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselist',
            options={'verbose_name': '题目范围', 'verbose_name_plural': '题目范围'},
        ),
    ]
