# Generated by Django 3.1.5 on 2021-01-23 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='诗词名称')),
                ('contents', models.TextField(verbose_name='诗词内容')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('video', models.CharField(max_length=50, verbose_name='视频/音频内容')),
                ('url', models.URLField(default='http://www.atguigu.com', verbose_name='视频链接')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_num', models.IntegerField(default=0, verbose_name='访问量')),
                ('desc', models.CharField(max_length=200, verbose_name='诗词简介')),
                ('down_lode', models.FileField(max_length=200, upload_to='source/', verbose_name='资源下载')),
                ('study_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('study_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '诗词信息',
                'verbose_name_plural': '诗词信息',
            },
        ),
        migrations.CreateModel(
            name='PoemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='poem/', verbose_name='诗词种类封面')),
                ('name', models.CharField(max_length=20, verbose_name='诗词种类名称')),
                ('study_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('study_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('desc', models.CharField(max_length=200, verbose_name='诗词种类简介')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '诗词种类信息',
                'verbose_name_plural': '诗词种类信息',
            },
        ),
        migrations.CreateModel(
            name='LessonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='诗词种类名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('courseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.PoemType',
                                                 verbose_name='所属诗词种类')),
            ],
            options={
                'verbose_name': '章节信息',
                'verbose_name_plural': '章节信息',
            },
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('down_load', models.FileField(max_length=200, upload_to='source/', verbose_name='资源下载路径')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.poem', verbose_name='所属诗词')),
            ],
            options={
                'verbose_name': '资源信息',
                'verbose_name_plural': '资源信息',
            },
        ),
        migrations.AddField(
            model_name='poem',
            name='poemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.poemtype', verbose_name='所属种类'),
        ),
        migrations.AddField(
            model_name='poem',
            name='poetinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poet.poetinfo', verbose_name='所属作者'),
        ),
    ]
