# Generated by Django 2.1.4 on 2021-03-20 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoninfo',
            options={'verbose_name': '诗词种类信息', 'verbose_name_plural': '诗词种类信息'},
        ),
        migrations.RemoveField(
            model_name='poem',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='down_lode',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='video',
        ),
        migrations.AddField(
            model_name='poem',
            name='note',
            field=models.TextField(default=' ', verbose_name='注释'),
        ),
        migrations.AddField(
            model_name='poem',
            name='translation',
            field=models.TextField(default=' ', verbose_name='译文'),
        ),
        migrations.AddField(
            model_name='poemtype',
            name='detail',
            field=models.TextField(default='', verbose_name='诗词种类详情'),
        ),
        migrations.AddField(
            model_name='poemtype',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.PoemType', verbose_name='所属诗词种类'),
        ),
    ]
