# Generated by Django 2.1.4 on 2021-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20210320_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='study_time',
        ),
    ]
