# Generated by Django 2.1.4 on 2021-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_remove_poemtype_study_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='video',
            field=models.CharField(default='1', max_length=50, verbose_name='视频/音频内容'),
        ),
    ]
