# Generated by Django 2.1.4 on 2021-03-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_poem_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='video',
        ),
    ]
