# Generated by Django 2.1.4 on 2021-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_remove_poem_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='url',
            field=models.URLField(default='http://www.baidu.com', verbose_name='视频链接'),
        ),
    ]
