# Generated by Django 2.1.4 on 2021-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_auto_20210330_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='url',
            field=models.TextField(default='http://www.baidu.com', max_length=200, verbose_name='视频链接'),
        ),
    ]
