# Generated by Django 2.1.4 on 2021-04-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0008_auto_20210424_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='url',
            field=models.CharField(default='暂无音频资源', max_length=200, verbose_name='视频链接'),
        ),
    ]
