# Generated by Django 2.1.4 on 2021-05-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_auto_20210424_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoninfo',
            name='courseinfo',
        ),
        migrations.RemoveField(
            model_name='sourceinfo',
            name='poem',
        ),
        migrations.DeleteModel(
            name='LessonInfo',
        ),
        migrations.DeleteModel(
            name='SourceInfo',
        ),
    ]
