# Generated by Django 2.1.4 on 2021-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0010_auto_20210531_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='url',
            field=models.CharField(default='暂无音频资源', max_length=200, verbose_name='音频链接'),
        ),
    ]
